SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


DROP TABLE IF EXISTS `mytbl_gender`;
CREATE TABLE IF NOT EXISTS `mytbl_gender` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `gender` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=2021134 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


INSERT INTO `mytbl_gender` (`id`, `gender`) VALUES
(1, 'W'),
(2, 'W'),
(3, 'W'),
(4, 'W'),
(5, 'M'),
(6, 'W'),
(7, 'W');
COMMIT;
